version: '3'
services:
  restyoursoap:
    image: restyoursoap_back
    container_name: restyoursoap_back
    build: .
    ports:
      - "7090:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
